# Generated by Django 5.0.3 on 2024-03-16 14:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kufar', '0002_furniture_delete_kufarparser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='furniture',
            options={'ordering': ['price'], 'verbose_name': 'Mieblia', 'verbose_name_plural': 'Jeblia'},
        ),
        migrations.AddField(
            model_name='furniture',
            name='parse_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
