# Generated by Django 5.0.3 on 2024-03-16 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kufar', '0003_alter_furniture_options_furniture_parse_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='furniture',
            options={'ordering': ['parse_datetime', 'price'], 'verbose_name': 'Mieblia', 'verbose_name_plural': 'Jeblia'},
        ),
    ]
